# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2019-02-20 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_auto_20190213_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='show',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='element',
            name='show',
            field=models.BooleanField(default=True),
        ),
    ]
